version: '3.8'

services:
  web:
    image: gguiyo/mi-aplicacion-php
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - APP_ENV=local

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    command: --init-file /docker-entrypoint-initdb.d/db.sql

volumes:
  db_data:
